apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./metallb/pool.yaml
- ./prometheus/longhorn.yaml
- ./cert-manager/issuer.yaml
- ./ingress/nginx-internal.yaml
- ./ingress/configmap.yaml
- ./secret/cloudflare.yaml
- ./secret/longhorn_backup.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: Kustomize
